path_pos = 'E:/Info/anu3/Licenta-git-2/Licenta/licenta/resources/input_data/sfa/train/positive'
path_neg = 'E:/Info/anu3/Licenta-git-2/Licenta/licenta/resources/input_data/sfa/train/negative'
path_models = 'E:/Info/anu3/Licenta-git-2/Licenta/licenta/texture_detection/models'
skin_label = 'skin'
non_skin_label = 'ns'
selected_classifier = 'svm_classifier_1000'
