path_pos = 'E:/Info/anu3/Licenta-git-2/Licenta/licenta/resources/input_data/skin/sfa/SKIN/7'
path_neg = 'E:/Info/anu3/Licenta-git-2/Licenta/licenta/resources/input_data/skin/sfa/NS/7'
path_models = 'E:/Info/anu3/Licenta-git-2/Licenta/licenta/texture_detection/models'
skin_label = 'skin'
non_skin_label = 'ns'
selected_classifier = 'svm_classifier_1000data_7area.pkl'
